version: '3'

services:
  mysql:
    profiles: [prod, dev]
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=lists
      - MYSQL_ROOT_PASSWORD=password

  soketi-dev:
    profiles: [dev]
    image: 'quay.io/soketi/soketi:1.6-16-alpine'
    entrypoint: /app/bin/server.js start --config=/configs/socketi-config.json
    volumes:
      - ./configs/dev:/configs
    ports:
      - '6001:6001'
      - '9601:9601'
  
  laravel-dev:
    profiles: [dev]
    image: bitnami/laravel:11
    depends_on:
      - mysql
      - soketi-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./dev-entrypoint.sh:/dev-entrypoint.sh
    entrypoint: /dev-entrypoint.sh
