version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=bitnami_myapp
      - MYSQL_ROOT_PASSWORD=password

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
      SOKETI_DEBUG: '0'
      SOKETI_METRICS_SERVER_PORT: '9601'
      SOKETI_DEFAULT_APP_ID: app-id
      SOKETI_DEFAULT_APP_KEY: app-key
      SOKETI_DEFAULT_APP_SECRET: app-secret
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
  
  laravel:
    image: bitnami/laravel:latest
    depends_on:
      - mysql
      - soketi
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - ./dev-entrypoint.sh:/dev-entrypoint.sh
    entrypoint: /dev-entrypoint.sh
